name: CI

on:
  pull_request:
    branches:
      - main
concurrency:
    group: ci-tests-${{ github.ref }}-1
    cancel-in-progress: true
jobs:
  
  build-test:
    strategy:
      matrix: 
        command: [lint, "test:ci", e2e]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress
            **/node_modules
          key: out-cache-yarn-${{ hashFiles('**/yarn.lock.json' )}}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn ${{ matrix.command }}
  echo:
    uses: rebeccafinne/jfokus/.github/workflows/_echo.yml@test
    with:
      message: "Hej hej!"



